# Generated by Django 4.1.1 on 2022-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fe_nacimiento', models.DateField(null=True)),
                ('edad', models.IntegerField()),
                ('descPariente', models.CharField(max_length=30)),
            ],
        ),
    ]
